spring.application.name=GestorApp
server.port=8081

# 1. Configuración de la Base de Datos (JPA/MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/gestor_gastos?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# -------------------------------------------------------------

# 2. Configuración del Servidor de Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aos1401aos@gmail.com
spring.mail.password=luaz poex gyrv pryp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 3. Configuración del Umbral de Alerta
app.alert.threshold=50.00
app.alert.recipient=aos1401aos@gmail.com